service: fight-reminders

plugins: 
  - serverless-stack-output
  - serverless-offline

frameworkVersion: "^2.0.0"
custom: 
  output:
    file: ./data.json
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    TOPIC_ARN: "arn:aws:sns:us-east-1:896748474789:fight-reminders"
    REMINDER_TABLE: "fight-reminders-dev-reminder-table"

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

    - Effect: Allow
      Resource:        
        - "arn:aws:dynamodb:us-east-1:896748474789:table/${self:service}-${self:custom.stage}-reminder-table"

      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

functions:
  authorizer:
    handler: src/authorizer.auth
    
  reminder:
    handler: src/reminder.publish
    events:
      - http:
          path: reminder
          method: post
          cors: true

  create-reminder:
    handler: src/create.reminder
    events:
      - http:
          path: create
          method: post
          cors: true

resources:
  Resources:
    ReminderTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        KeySchema:
          - AttributeName: scorecardId
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: scorecardId
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:service}-${self:custom.stage}-reminder-table